In [18]:
import numpy as np


In [19]:
np_array = np.array([1, 2, 3, 4, 5]) # Array de numpy
array = [1, 2, 3, 4, 5] # Array de python
print(np_array)
print(array)


[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [20]:
print(array + [10])
print(np_array + 10)

[1, 2, 3, 4, 5, 10]
[11 12 13 14 15]


In [21]:
np_array.shape

(5,)

In [22]:
np_array = np.array([[1, 2, 3, 4], [6, 7, 8, 9]])
np_array.shape


(2, 4)

In [23]:
np_array[0]

array([1, 2, 3, 4])